-- create tables

CREATE TABLE COFFEE (ID NUMERIC(19) IDENTITY NOT NULL, NAME VARCHAR(255) NULL, PRICE FLOAT(32) NULL, PRIMARY KEY (ID))

CREATE TABLE COFFEE_AUDIT (AUDIT_ID NUMERIC(19) IDENTITY NOT NULL, COFFEE_ID NUMERIC(19) NOT NULL, NAME VARCHAR(255) NULL, PRICE FLOAT(32) NULL, PRIMARY KEY (AUDIT_ID))

-- create trigger
CREATE TRIGGER dbo.coffeetrigger on dbo.COFFEE 
AFTER INSERT
as BEGIN 
SET NOCOUNT ON;
INSERT INTO dbo.COFFEE_AUDIT(
        COFFEE_ID,
        NAME,
        PRICE
    )
    SELECT
        i.ID,
        i.NAME,
        i.PRICE
    FROM
        inserted i
END

-- drop trigger
-- DROP TRIGGER dbo.coffeetrigger